#PinterestLike/UserBundle/Resources/services.yml
parameters:
    my_user_provider.class: PinterestLike\UserBundle\Security\Core\User\FOSUBUserProvider
 
services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id, yahoo: yahoo_id}, @session]

#    PinterestLike_user_upload_listener:
#        class: PinterestLike\UserBundle\EventListener\UploadListener
#        tags:
#            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
#        arguments: ['@doctrine']
