<?php

namespace PinterestLike\VendorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ColourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColourRepository extends EntityRepository
{
    public function findForList()
    {
        /** @var EntityManager $entityManager */
        return $this->createQueryBuilder('c')
            // ->andWhere('d.user = :user')
            // ->setParameter('user',$user)
            ->leftJoin('PinterestLikeVendorBundle:VendorImage', 'vi', 'WITH', 'vi.colour = c')
            ->leftJoin('PinterestLikeVendorBundle:VendorVideo', 'vv', 'WITH', 'vv.colour = c')
            ->where('vi IS NOT NULL OR vv IS NOT NULL')
            ->getQuery()
            ->getResult();
    }
}
