<?php

namespace PinterestLike\VendorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VendorQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorQuestionRepository extends EntityRepository
{
}
