<?php

namespace PinterestLike\VendorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VendorBusinessHoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorBusinessHoursRepository extends EntityRepository
{
}
